# GOFR-DIG Docker Compose - Complete Production Stack
#
# Port Configuration:
#   All ports defined in lib/gofr-common/config/gofr_ports.env
#   Must be exported to environment before running docker compose
# 
# OpenWebUI Integration:
#   OpenWebUI connects to MCPO which exposes MCP tools as REST endpoints.
#   Configure OpenWebUI to use: http://localhost:${GOFR_DIG_MCPO_PORT}
#
# Usage:
#   Use start-prod.sh to start production stack (recommended)
#   OR manually:
#     cd docker
#     set -a && source ../lib/gofr-common/config/gofr_ports.env && set +a
#     docker compose up -d
#
# Services:
#   - neo4j:    Graph Database - ports ${GOFR_NEO4J_HTTP_PORT}, ${GOFR_NEO4J_BOLT_PORT}
#   - chromadb: Vector Database - port ${GOFR_CHROMA_PORT}
#   - mcp:      MCP Server (Core Logic) - port ${GOFR_DIG_MCP_PORT}
#   - mcpo:     MCPO Server (OpenAPI for OpenWebUI) - port ${GOFR_DIG_MCPO_PORT}
#   - web:      Web Server (Health Check Only) - port ${GOFR_DIG_WEB_PORT}

name: gofr-dig

x-gofr-ports: &gofr_ports
  env_file:
    - ../lib/gofr-common/config/gofr_ports.env

services:
  # ============================================================================
  # INFRASTRUCTURE (Shared, external Vault consumed)
  # ============================================================================

  neo4j:
    <<: *gofr_ports
    image: gofr-dig-neo4j:latest
    container_name: gofr-neo4j
    hostname: gofr-neo4j
    restart: unless-stopped
    ports:
      - "${GOFR_NEO4J_HTTP_PORT}:7474"
      - "${GOFR_NEO4J_BOLT_PORT}:7687"
    volumes:
      - gofr-dig-neo4j-data:/data
      - gofr-dig-neo4j-logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - gofr-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${GOFR_NEO4J_HTTP_INTERNAL_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  chromadb:
    <<: *gofr_ports
    image: gofr-dig-chromadb:latest
    container_name: gofr-chromadb
    hostname: gofr-chromadb
    restart: unless-stopped
    ports:
      - "${GOFR_CHROMA_PORT}:8000"
    volumes:
      - gofr-dig-chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - gofr-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GOFR_CHROMA_INTERNAL_PORT}/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ==========================================================================
  # 1. MCP Server (Core Logic)
  # ==========================================================================
  mcp:
    <<: *gofr_ports
    image: gofr-dig-prod:latest
    container_name: gofr-dig-mcp
    hostname: gofr-dig-mcp
    restart: unless-stopped
    user: gofr-dig
    working_dir: /home/gofr-dig
    entrypoint: []
    depends_on:
      neo4j:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    command: >
      /home/gofr-dig/.venv/bin/python -m app.main_mcp
      --host 0.0.0.0 --port ${GOFR_DIG_MCP_PORT}
    environment:
      - GOFR_DIG_ENV=PROD
      - GOFR_DIG_MCP_PORT=${GOFR_DIG_MCP_PORT}
      - GOFR_DIG_LOG_LEVEL=${GOFR_DIG_LOG_LEVEL:-INFO}
      - GOFR_DIG_LOG_FILE=/home/gofr-dig/logs/gofr-dig-mcp.log
      - GOFR_DIG_AUTH_DISABLED=false
      # JWT Secret and Neo4j password loaded from Vault via AppRole (Zero-Trust Bootstrap)
      - GOFR_DIG_JWT_SECRET=${GOFR_DIG_JWT_SECRET}
      - GOFR_DIG_NEO4J_PASSWORD=${NEO4J_PASSWORD}
      # Auth Backend (Vault) - shared across all GOFR services
      - GOFR_AUTH_BACKEND=vault
      - GOFR_VAULT_URL=http://gofr-vault:${GOFR_VAULT_PORT}
      - GOFR_VAULT_TOKEN=${VAULT_ROOT_TOKEN:-gofr-dev-root-token}
      - GOFR_VAULT_PATH_PREFIX=gofr/auth
      - GOFR_VAULT_MOUNT_POINT=secret
      # Infrastructure connections
      - GOFR_DIG_CHROMADB_HOST=gofr-chromadb
      - GOFR_DIG_CHROMADB_PORT=${GOFR_CHROMA_INTERNAL_PORT}
      - GOFR_DIG_NEO4J_URI=bolt://gofr-neo4j:${GOFR_NEO4J_BOLT_INTERNAL_PORT}
      - GOFR_DIG_NEO4J_USER=neo4j
      # LLM Configuration
      - GOFR_DIG_OPENROUTER_API_KEY=${GOFR_DIG_OPENROUTER_API_KEY:-}
      - GOFR_DIG_OPENROUTER_BASE_URL=${GOFR_DIG_OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      - GOFR_DIG_LLM_MODEL=${GOFR_DIG_LLM_MODEL:-meta-llama/llama-3.1-70b-instruct}
      - GOFR_DIG_EMBEDDING_MODEL=${GOFR_DIG_EMBEDDING_MODEL:-qwen/qwen3-embedding-8b}
      - GOFR_DIG_LLM_TIMEOUT=${GOFR_DIG_LLM_TIMEOUT:-60}
      - GOFR_DIG_LLM_MAX_RETRIES=${GOFR_DIG_LLM_MAX_RETRIES:-3}
    ports:
      - "${GOFR_DIG_MCP_PORT}:${GOFR_DIG_MCP_PORT}"
    volumes:
      - gofr-dig-data:/home/gofr-dig/data
      - gofr-dig-prod-logs:/home/gofr-dig/logs
      # AppRole credentials (Zero-Trust Bootstrap)
      # Path goes through lib/gofr-common/secrets (canonical location)
      - ${HOST_PROJECT_ROOT:-..}/lib/gofr-common/secrets/service_creds/gofr-mcp.json:/run/secrets/vault_creds:ro
    networks:
      - gofr-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${GOFR_DIG_MCP_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # ==========================================================================
  # 2. MCPO Server (OpenAPI Wrapper)
  # ==========================================================================
  mcpo:
    <<: *gofr_ports
    image: gofr-dig-prod:latest
    container_name: gofr-dig-mcpo
    hostname: gofr-dig-mcpo
    restart: unless-stopped
    user: gofr-dig
    working_dir: /home/gofr-dig
    entrypoint: []
    depends_on:
      mcp:
        condition: service_healthy
    command: >
      /home/gofr-dig/.venv/bin/mcpo
      --host 0.0.0.0 --port ${GOFR_DIG_MCPO_PORT} --server-type streamable-http
      -- http://gofr-dig-mcp:${GOFR_DIG_MCP_PORT}/mcp
    environment:
      - GOFR_DIG_ENV=PROD
      - GOFR_DIG_MCP_PORT=${GOFR_DIG_MCP_PORT}
      - GOFR_DIG_MCPO_PORT=${GOFR_DIG_MCPO_PORT}
      - GOFR_DIG_LOG_LEVEL=${GOFR_DIG_LOG_LEVEL:-INFO}
      - GOFR_DIG_LOG_FILE=/home/gofr-dig/logs/gofr-dig-mcpo.log
    ports:
      - "${GOFR_DIG_MCPO_PORT}:${GOFR_DIG_MCPO_PORT}"
    volumes:
      - gofr-dig-prod-logs:/home/gofr-dig/logs
    networks:
      - gofr-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${GOFR_DIG_MCPO_PORT}/openapi.json || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  # ==========================================================================
  # 3. Web Server (Health Check Only)
  # ==========================================================================
  web:
    <<: *gofr_ports
    image: gofr-dig-prod:latest
    container_name: gofr-dig-web
    hostname: gofr-dig-web
    restart: unless-stopped
    user: gofr-dig
    working_dir: /home/gofr-dig
    entrypoint: []
    command: >
      /home/gofr-dig/.venv/bin/python -m app.main_web
      --host 0.0.0.0 --port ${GOFR_DIG_WEB_PORT}
    environment:
      - GOFR_DIG_ENV=PROD
      - GOFR_DIG_WEB_PORT=${GOFR_DIG_WEB_PORT}
      - GOFR_DIG_LOG_LEVEL=${GOFR_DIG_LOG_LEVEL:-INFO}
      - GOFR_DIG_LOG_FILE=/home/gofr-dig/logs/gofr-dig-web.log
    ports:
      - "${GOFR_DIG_WEB_PORT}:${GOFR_DIG_WEB_PORT}"
    volumes:
      # AppRole credentials (Zero-Trust Bootstrap)
      # Path goes through lib/gofr-common/secrets (canonical location)
      - ${HOST_PROJECT_ROOT:-..}/lib/gofr-common/secrets/service_creds/gofr-web.json:/run/secrets/vault_creds:ro
      - gofr-dig-prod-logs:/home/gofr-dig/logs
    networks:
      - gofr-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${GOFR_DIG_WEB_PORT}/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

# ==========================================================================
# Networks
# ==========================================================================
networks:
  gofr-net:
    name: gofr-net
    external: true
    # Network is shared across dev container, infra scripts, and compose
    # Create manually if needed: docker network create gofr-net

# ==========================================================================
# Volumes - Persistent
# ==========================================================================
# Volumes
# ==========================================================================
volumes:
  gofr-dig-neo4j-data:
    name: gofr-dig-neo4j-data
    external: false
  gofr-dig-neo4j-logs:
    name: gofr-dig-neo4j-logs
    external: false
  gofr-dig-chroma-data:
    name: gofr-dig-chroma-data
    external: false
  gofr-dig-data:
    name: gofr-dig-data
    external: false
  gofr-dig-backups:
    name: gofr-dig-backups
    external: false
  gofr-dig-prod-logs:
    name: gofr-dig-prod-logs